### ISSUE TITLE
Error on /checkowner

### ISSUE THREAD

**Issue by Sadisticrabbit** [SDPlugins/Owner-Checker#2]
Error appears to be related to showing the characters name. A very useful feature. Instead it just shows the steam id (64)

An error occured while executing checkowner []: System.NullReferenceException: Object reference not set to an instance of an object
  at Rocket.Unturned.Player.UnturnedPlayer.get_CharacterName () [0x00000] in <filename unknown>:0
  at SDPlugins.Library.TellInfo (IRocketPlayer caller, Rocket.Unturned.Player.UnturnedPlayer owner, CSteamID ownerid, CSteamID group) [0x00000]             in <filename unknown>:0
  at SDPlugins.CheckOwner.Execute (IRocketPlayer caller, System.String[] command) [0x00000] in <filename unknown>:0
  at Rocket.Core.Commands.RocketCommandManager+RegisteredRocketCommand.Execute (IRocketPlayer caller, System.String[] command) [0x00000] in <fi            lename unknown>:0
  at Rocket.Core.Commands.RocketCommandManager.Execute (IRocketPlayer player, System.String command) [0x00000] in <filename unknown>:0 ^CuEssen      Client has executed command "An error occured while executing checkowner []: System.NullReferenceException: Object reference not set to an instance of an object"
Client has executed command "  at Rocket.Unturned.Player.UnturnedPlayer.get_CharacterName () [0x00000] in <filename unknown>:0"
Client has executed command "  at SDPlugins.Library.TellInfo (IRocketPlayer caller, Rocket.Unturned.Player.UnturnedPlayer owner, CSteamID ownerid, CSteamID group) [0x00000]             in <filename unknown>:0"
Client has executed command "  at SDPlugins.CheckOwner.Execute (IRocketPlayer caller, System.String[] command) [0x00000] in <filename unknown>:0"
Client has executed command "  at Rocket.Core.Commands.RocketCommandManager+RegisteredRocketCommand.Execute (IRocketPlayer caller, System.String[] command)

**Comment by snowball7275** [comment]
Should be fixed.

**Comment by SDPlugins** [comment]
Should be fixed in the latest build.

**Comment by Sadisticrabbit** [comment]
Thanks for the update. I have updated it on my server and we are now getting it partly working. It seems to return a name, but we are still getting this error in the console:

Rocket.Unturned >> Exception in handleChat: System.NullReferenceException: Object reference not set to an instance of an object

  at Rocket.Unturned.Player.UnturnedPlayer.get_CharacterName () [0x00000] in :0

  at DefCon42.CheckOwner.Execute (IRocketPlayer caller, System.String[] command) [0x00000] in :0

  at DefCon42.PlayerHandler.UnturnedEvents_OnPlayerChatted (Rocket.Unturned.Player.UnturnedPlayer player, UnityEngine.Color& color, System.String message, EChatMode chatMode, System.Boolean& cancel) [0x00000] in :0

  at Rocket.Unturned.Events.UnturnedPlayerEvents.firePlayerChatted (Rocket.Unturned.Player.UnturnedPlayer player, EChatMode chatMode, Color color, System.String msg, System.Boolean& cancel) [0x00000] in :0 ^C

**Comment by SDPlugins** [comment]
Hm.. Alright, give me a moment. It seems like you still must have an older build, since the namespace is still off. I'll check whether I messed something up somewhere.

**Comment by SDPlugins** [comment]
Ok, could you tell me the specifics of when this happens;

a) Was the owner of the structure online?
b) What structure did you attempt to use /checkowner on?
c) Are there any other def

**Comment by Sadisticrabbit** [comment]
HI There, 

Thanks for your time. 

A: No, the owner was not online. 
B: It was a pine roof, and I also tried a pine stairs.
C: -
Playerinfolib appears to be v1.3.0.1
SDPlugins_Owner Cheker.dll is v 1.0.0.0 and is 10Kbs in size. Date modified is 16th May 2017 @ 12:41

It seems to work when the player is online. You get all the details, Steam ID, Name, Character Name, Group ID, Group Name. It all works with no error when the are on. 

When they are not you get the error. It **does** return the Steam ID, the steam name, the group ID and the group name. It **does not** return the character name. It shows "Could not get character name" and the previously mentioned error happens in the log. 

I have confirmed that one of the users I get the error on is in the database and has both the player name and character name. 

It does not appear to matter what I check, any object will cause the error if the user is not online. 

Hope this helps.

**Comment by SDPlugins** [comment]
Do you have UsePlayerInfoLib set to true in the config?

I tried with it both enabled and disabled in the configuration file, and I'm still unable to replicate the issue, I'm surprised that it returns all of the data even after the error; that's interesting.

**Comment by Sadisticrabbit** [comment]
I have it set to true. 
I'm going to reset the server (it's a secondary so no big deal) and start from scratch. Hopefully this will clear it out because if you can't replicate it then it must be something weird my end. 

Thanks for all your help. I'll let you know if it still does it after a rebuild.
